import base64
import os
import sys

import matplotlib.pyplot as plt
import numpy as np
import streamlit as st
import tensorflow as tf
from dotenv import load_dotenv
from huggingface_hub import hf_hub_download
from openai import OpenAI
from PIL import Image

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from utils.predict import CLASSES, compute_saliency, predict

load_dotenv(os.path.join(os.path.dirname(__file__), '..', '.env'))

# Set via HF Space secret or .env — e.g. "yourusername/brain-tumor-models"
HF_MODEL_REPO = os.getenv('HF_MODEL_REPO', '')

st.set_page_config(page_title='Brain Tumor MRI Classification', layout='wide')

MODEL_PATHS = {
    'Custom CNN': (
        os.path.join(os.path.dirname(__file__), '..', 'models', 'custom_cnn_brain_tumor.keras'),
        (224, 224),
    ),
    'Xception': (
        os.path.join(os.path.dirname(__file__), '..', 'models', 'xception_model.weights.keras'),
        (299, 299),
    ),
}

OPENAI_MODELS = {
    'GPT-4o':      'gpt-4o',
    'GPT-4o mini': 'gpt-4o-mini',
}

CLASS_INFO = {
    'glioma': {
        'name': 'Glioma',
        'description': 'A tumor arising from glial cells in the brain or spinal cord.',
        'subtypes': 'Astrocytoma, Oligodendroglioma, Glioblastoma (GBM)',
        'prevalence': '~33% of all brain tumors',
        'severity': 'High',
        'color': '#D94F4F',
    },
    'meningioma': {
        'name': 'Meningioma',
        'description': 'A tumor that forms on the meninges — membranes surrounding the brain and spinal cord.',
        'subtypes': 'Grade I (benign ~80%), Grade II (atypical), Grade III (anaplastic)',
        'prevalence': '~37% of all brain tumors',
        'severity': 'Moderate',
        'color': '#E07B00',
    },
    'no_tumor': {
        'name': 'No Tumor Detected',
        'description': 'No tumor detected in this MRI scan.',
        'subtypes': 'N/A',
        'prevalence': 'N/A',
        'severity': 'None',
        'color': '#1A9E52',
    },
    'pituitary': {
        'name': 'Pituitary Tumor',
        'description': 'A tumor that forms in the pituitary gland at the base of the brain.',
        'subtypes': 'Adenoma (most common), Craniopharyngioma (rare)',
        'prevalence': '~17% of all brain tumors',
        'severity': 'Low–Moderate',
        'color': '#2B6CB0',
    },
}


def _ensure_model_file(path: str) -> str | None:
    """Return path if the file exists locally; otherwise download from HF Hub."""
    if os.path.exists(path):
        return path
    if not HF_MODEL_REPO:
        return None
    try:
        return hf_hub_download(
            repo_id=HF_MODEL_REPO,
            filename=os.path.basename(path),
            local_dir='/tmp/hf_models',
            token=False,
        )
    except Exception as e:
        st.error(f'Could not download {os.path.basename(path)} from HF Hub: {e}')
        return None


@st.cache_resource
def load_model(path: str) -> tf.keras.Model | None:
    resolved = _ensure_model_file(path)
    if not resolved:
        return None
    try:
        return tf.keras.models.load_model(resolved)
    except Exception:
        return None


def _b64(img_bytes: bytes) -> str:
    return base64.b64encode(img_bytes).decode()


def _image_message(img_bytes: bytes, text: str) -> dict:
    return {
        'role': 'user',
        'content': [
            {'type': 'text', 'text': text},
            {'type': 'image_url', 'image_url': {
                'url': f'data:image/jpeg;base64,{_b64(img_bytes)}', 'detail': 'high',
            }},
        ],
    }


def _prediction_summary(results: dict) -> str:
    return '\n'.join(
        f'- {name}: {CLASS_INFO[r["class"]]["name"]} ({r["confidence"]:.1%} confidence)'
        for name, r in results.items()
    )


def _prob_bar(label: str, prob: float, color: str) -> None:
    st.markdown(
        f"<div style='display:flex;align-items:center;gap:10px;margin:5px 0'>"
        f"<span style='width:150px;font-size:0.85em;color:#374151'>{label}</span>"
        f"<div style='flex:1;background:#E5E7EB;border-radius:3px;height:14px'>"
        f"<div style='width:{prob * 100:.1f}%;background:{color};height:14px;border-radius:3px'></div></div>"
        f"<span style='width:42px;text-align:right;font-size:0.85em;color:#374151'>{prob:.1%}</span>"
        f"</div>",
        unsafe_allow_html=True,
    )


# ── Sidebar ────────────────────────────────────────────────────────────────────

api_key = os.getenv('OPENAI_API_KEY', '')

with st.sidebar:
    st.header('Configuration')

    st.subheader('Classification Models')
    model_enabled  = {name: st.checkbox(name, value=True) for name in MODEL_PATHS}
    enabled_models = {n: MODEL_PATHS[n] for n, on in model_enabled.items() if on}

    st.divider()
    st.subheader('Language Model')
    selected_llm_name = st.selectbox('Select model', list(OPENAI_MODELS.keys()))
    selected_llm_id   = OPENAI_MODELS[selected_llm_name]

    st.divider()
    st.caption(
        'Results are generated by deep learning models and are intended for '
        'research and educational purposes only. They do not constitute medical advice.'
    )


# ── Header ─────────────────────────────────────────────────────────────────────

st.title('Brain Tumor MRI Classification')
st.caption(
    'Upload a brain MRI scan for automated multi-model classification. '
    'Predictions are research-grade and should not replace clinical diagnosis.'
)
st.divider()

# ── Upload ─────────────────────────────────────────────────────────────────────

uploaded = st.file_uploader(
    'Upload MRI scan (JPG or PNG)',
    type=['jpg', 'jpeg', 'png'],
)

results: dict   = {}
img_bytes: bytes | None = None

if uploaded:
    img_bytes = uploaded.read()
    tmp_path  = f'/tmp/{uploaded.name}'
    with open(tmp_path, 'wb') as f:
        f.write(img_bytes)

    # ── Image + prediction summary ─────────────────────────────────────────────

    col_img, col_res = st.columns([1, 2], gap='large')

    with col_img:
        st.image(img_bytes, use_container_width=True)
        st.caption(uploaded.name)

    with col_res:
        if not enabled_models:
            st.warning('Enable at least one model in the sidebar.')
        else:
            with st.spinner('Running classification…'):
                for name, (path, size) in enabled_models.items():
                    model = load_model(path)
                    if model is None:
                        st.error(f'Model weights not found: {name}')
                        continue
                    results[name] = predict(model, tmp_path, size)
                    results[name]['model'] = model

        if results:
            for name, r in results.items():
                info  = CLASS_INFO[r['class']]
                color = info['color']
                st.markdown(
                    f"<div style='border-left:4px solid {color};padding:10px 16px;"
                    f"background:#F9FAFB;border-radius:0 6px 6px 0;margin-bottom:12px'>"
                    f"<div style='font-size:0.75em;font-weight:600;color:#6B7280;"
                    f"text-transform:uppercase;letter-spacing:0.06em;margin-bottom:4px'>{name}</div>"
                    f"<div style='font-size:1.15em;font-weight:700;color:{color}'>{info['name']}</div>"
                    f"<div style='font-size:0.85em;color:#6B7280;margin-top:2px'>"
                    f"Confidence: <strong>{r['confidence']:.1%}</strong></div>"
                    f"</div>",
                    unsafe_allow_html=True,
                )

            classes = [r['class'] for r in results.values()]
            if len(results) > 1:
                if len(set(classes)) == 1:
                    st.success(f"Both models agree: **{CLASS_INFO[classes[0]]['name']}**")
                else:
                    parts = ' | '.join(
                        f"{n}: {CLASS_INFO[r['class']]['name']}" for n, r in results.items()
                    )
                    st.warning(f'Model predictions differ — {parts}')

# ── Analysis tabs ──────────────────────────────────────────────────────────────

if results:
    st.divider()
    tab_probs, tab_compare, tab_report, tab_chat = st.tabs(
        ['Class Probabilities', 'Model Comparison', 'Clinical Report', 'Image Analysis']
    )

    # ── Tab 1: per-model probability bars ─────────────────────────────────────

    with tab_probs:
        cols = st.columns(len(results), gap='large')
        for col, (name, r) in zip(cols, results.items()):
            with col:
                st.markdown(f'**{name}**')
                for cls in CLASSES:
                    _prob_bar(CLASS_INFO[cls]['name'], r['probabilities'][cls], CLASS_INFO[cls]['color'])

                if r['class'] != 'no_tumor':
                    info = CLASS_INFO[r['class']]
                    with st.expander('Tumor profile'):
                        m1, m2 = st.columns(2)
                        m1.metric('Severity', info['severity'])
                        m2.metric('Prevalence', info['prevalence'])
                        st.caption(f"**Subtypes:** {info['subtypes']}")
                        st.caption(info['description'])

    # ── Tab 2: side-by-side comparison ────────────────────────────────────────

    with tab_compare:
        if len(results) < 2:
            st.info('Enable both classification models in the sidebar to see a side-by-side comparison.')
        else:
            sub_dist, sub_sal = st.tabs(['Probability Distribution', 'Saliency Maps'])

            with sub_dist:
                n   = len(results)
                fig, axes = plt.subplots(1, n, figsize=(6 * n, 4), squeeze=False)
                for ax, (name, r) in zip(axes[0], results.items()):
                    labels = [CLASS_INFO[c]['name'] for c in CLASSES]
                    probs  = [r['probabilities'][c] for c in CLASSES]
                    colors = [CLASS_INFO[c]['color'] for c in CLASSES]
                    bars   = ax.barh(labels, probs, color=colors, edgecolor='none', height=0.55)
                    ax.set_xlim(0, 1)
                    ax.set_title(name, fontweight='bold', pad=10)
                    ax.set_xlabel('Probability')
                    ax.spines[['top', 'right']].set_visible(False)
                    ax.tick_params(axis='y', labelsize=10)
                    for bar, p in zip(bars, probs):
                        ax.text(
                            min(p + 0.015, 0.93),
                            bar.get_y() + bar.get_height() / 2,
                            f'{p:.1%}', va='center', fontsize=9,
                        )
                plt.tight_layout(pad=1.5)
                st.pyplot(fig)
                plt.close(fig)

            with sub_sal:
                n   = len(results)
                fig, axes = plt.subplots(2, n, figsize=(5 * n, 8), squeeze=False)
                fig.patch.set_facecolor('#FFFFFF')
                for ci, (name, r) in enumerate(results.items()):
                    img_arr = r['image_array']
                    sal     = compute_saliency(r['model'], img_arr)
                    axes[0][ci].imshow(img_arr)
                    axes[0][ci].set_title(name, fontweight='bold', pad=8)
                    axes[0][ci].axis('off')
                    axes[1][ci].imshow(img_arr)
                    axes[1][ci].imshow(sal, cmap='hot', alpha=0.45)
                    axes[1][ci].set_title(f'{name} — Activation', fontweight='bold', pad=8)
                    axes[1][ci].axis('off')
                fig.text(0.005, 0.73, 'Original', va='center', rotation='vertical',
                         fontsize=10, color='#555')
                fig.text(0.005, 0.27, 'Saliency', va='center', rotation='vertical',
                         fontsize=10, color='#555')
                plt.tight_layout(pad=1.2)
                st.pyplot(fig)
                plt.close(fig)

    # ── Tab 3: clinical report ─────────────────────────────────────────────────

    with tab_report:
        st.markdown(
            'Generate a structured clinical summary based on the classification results and the uploaded MRI.'
        )
        if not api_key:
            st.warning('Enter an OpenAI API key in the sidebar to generate a report.')
        else:
            if st.button('Generate Report', type='primary'):
                prompt = (
                    'You are a neuroradiology AI assistant. Based on the brain MRI scan and the '
                    'model predictions listed below, write a comprehensive clinical report with '
                    'the following eight sections:\n'
                    '1. Executive Summary\n'
                    '2. Imaging Findings\n'
                    '3. Classification Results\n'
                    '4. Differential Diagnosis\n'
                    '5. Tumor Characteristics\n'
                    '6. Historical Context and Similar Cases\n'
                    '7. Recommended Next Steps\n'
                    '8. Disclaimer\n\n'
                    f'Model predictions:\n{_prediction_summary(results)}\n\n'
                    'Use a markdown heading (##) for each section. '
                    'Write in clinical but accessible language.'
                )
                with st.spinner('Generating report…'):
                    client = OpenAI(api_key=api_key)
                    resp   = client.chat.completions.create(
                        model=selected_llm_id,
                        messages=[_image_message(img_bytes, prompt)],
                        max_tokens=2000,
                    )
                report = resp.choices[0].message.content
                st.markdown(report)
                st.download_button(
                    'Download Report (Markdown)',
                    data=report,
                    file_name='mri_classification_report.md',
                    mime='text/markdown',
                )

    # ── Tab 4: multi-turn image chat ───────────────────────────────────────────

    with tab_chat:
        if not api_key:
            st.warning('Enter an OpenAI API key in the sidebar to use image analysis.')
        else:
            if 'chat_history' not in st.session_state:
                st.session_state.chat_history = []

            col_desc, col_clear = st.columns([5, 1])
            col_desc.caption(
                'Ask questions about this MRI. The model has access to both the image and the classification results.'
            )
            if col_clear.button('Clear history', use_container_width=True):
                st.session_state.chat_history = []
                st.rerun()

            for msg in st.session_state.chat_history:
                with st.chat_message(msg['role']):
                    st.markdown(msg['content'])

            user_input = st.chat_input('Ask about this MRI scan…')
            if user_input and img_bytes:
                st.session_state.chat_history.append({'role': 'user', 'content': user_input})
                with st.chat_message('user'):
                    st.markdown(user_input)

                system_ctx = (
                    'You are a neuroradiology AI assistant. '
                    'Answer questions about the brain MRI image concisely and accurately. '
                    f'Classification results: {_prediction_summary(results)}'
                )
                api_messages = [{'role': 'system', 'content': system_ctx}]
                for turn in st.session_state.chat_history[:-1]:
                    api_messages.append({'role': turn['role'], 'content': turn['content']})
                api_messages.append(_image_message(img_bytes, user_input))

                client = OpenAI(api_key=api_key)
                with st.chat_message('assistant'):
                    with st.spinner(''):
                        resp = client.chat.completions.create(
                            model=selected_llm_id,
                            messages=api_messages,
                            max_tokens=800,
                        )
                    answer = resp.choices[0].message.content
                    st.markdown(answer)
                st.session_state.chat_history.append({'role': 'assistant', 'content': answer})
